/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BloodGroup = { 'AB_neg' : null } |
  { 'AB_pos' : null } |
  { 'B_neg' : null } |
  { 'B_pos' : null } |
  { 'A_neg' : null } |
  { 'A_pos' : null } |
  { 'O_neg' : null } |
  { 'O_pos' : null };
export interface Donor {
  'id' : bigint,
  'status' : DonorStatus,
  'name' : string,
  'bloodGroup' : BloodGroup,
  'phoneNumber' : string,
}
export type DonorStatus = { 'active' : null } |
  { 'permanentlyRejected' : null } |
  { 'appointed' : { 'appointmentDate' : Time, 'patientName' : string } } |
  { 'temporarilyRejected' : { 'availableDate' : Time } };
export type Time = bigint;
export interface _SERVICE {
  'addDonor' : ActorMethod<
    [string, BloodGroup, string],
    { 'ok' : bigint } |
      { 'error' : string }
  >,
  'getAllAppointedDonors' : ActorMethod<[], Array<Donor>>,
  'getAllDonors' : ActorMethod<[], Array<Donor>>,
  'getAllPermanentlyRejectedDonors' : ActorMethod<[], Array<Donor>>,
  'getAllTempRejectedDonors' : ActorMethod<[], Array<Donor>>,
  'getDonor' : ActorMethod<[bigint], { 'ok' : Donor } | { 'error' : string }>,
  'getDonorsByBloodGroup' : ActorMethod<[BloodGroup], Array<Donor>>,
  'updateDonorStatus' : ActorMethod<
    [bigint, DonorStatus],
    { 'ok' : null } |
      { 'error' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];