/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BloodGroup = IDL.Variant({
  'AB_neg' : IDL.Null,
  'AB_pos' : IDL.Null,
  'B_neg' : IDL.Null,
  'B_pos' : IDL.Null,
  'A_neg' : IDL.Null,
  'A_pos' : IDL.Null,
  'O_neg' : IDL.Null,
  'O_pos' : IDL.Null,
});
export const Time = IDL.Int;
export const DonorStatus = IDL.Variant({
  'active' : IDL.Null,
  'permanentlyRejected' : IDL.Null,
  'appointed' : IDL.Record({
    'appointmentDate' : Time,
    'patientName' : IDL.Text,
  }),
  'temporarilyRejected' : IDL.Record({ 'availableDate' : Time }),
});
export const Donor = IDL.Record({
  'id' : IDL.Nat,
  'status' : DonorStatus,
  'name' : IDL.Text,
  'lastCalledDate' : IDL.Opt(IDL.Int),
  'bloodGroup' : BloodGroup,
  'phoneNumber' : IDL.Text,
  'callCount' : IDL.Int,
});

export const idlService = IDL.Service({
  'addDonor' : IDL.Func([IDL.Text, BloodGroup, IDL.Text], [IDL.Nat], []),
  'deleteDonor' : IDL.Func([IDL.Nat], [], []),
  'editDonor' : IDL.Func([IDL.Nat, IDL.Text, BloodGroup, IDL.Text], [], []),
  'getAllAppointedDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
  'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
  'getAllPermanentlyRejectedDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
  'getAllTempRejectedDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
  'getDonor' : IDL.Func([IDL.Nat], [Donor], ['query']),
  'getDonorsByBloodGroup' : IDL.Func([BloodGroup], [IDL.Vec(Donor)], ['query']),
  'markDonorAsDonated' : IDL.Func([IDL.Nat], [], []),
  'markDonorAsNotDonated' : IDL.Func([IDL.Nat], [], []),
  'recordCall' : IDL.Func([IDL.Nat], [], []),
  'updateDonorStatus' : IDL.Func([IDL.Nat, DonorStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BloodGroup = IDL.Variant({
    'AB_neg' : IDL.Null,
    'AB_pos' : IDL.Null,
    'B_neg' : IDL.Null,
    'B_pos' : IDL.Null,
    'A_neg' : IDL.Null,
    'A_pos' : IDL.Null,
    'O_neg' : IDL.Null,
    'O_pos' : IDL.Null,
  });
  const Time = IDL.Int;
  const DonorStatus = IDL.Variant({
    'active' : IDL.Null,
    'permanentlyRejected' : IDL.Null,
    'appointed' : IDL.Record({
      'appointmentDate' : Time,
      'patientName' : IDL.Text,
    }),
    'temporarilyRejected' : IDL.Record({ 'availableDate' : Time }),
  });
  const Donor = IDL.Record({
    'id' : IDL.Nat,
    'status' : DonorStatus,
    'name' : IDL.Text,
    'lastCalledDate' : IDL.Opt(IDL.Int),
    'bloodGroup' : BloodGroup,
    'phoneNumber' : IDL.Text,
    'callCount' : IDL.Int,
  });
  
  return IDL.Service({
    'addDonor' : IDL.Func([IDL.Text, BloodGroup, IDL.Text], [IDL.Nat], []),
    'deleteDonor' : IDL.Func([IDL.Nat], [], []),
    'editDonor' : IDL.Func([IDL.Nat, IDL.Text, BloodGroup, IDL.Text], [], []),
    'getAllAppointedDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
    'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
    'getAllPermanentlyRejectedDonors' : IDL.Func(
        [],
        [IDL.Vec(Donor)],
        ['query'],
      ),
    'getAllTempRejectedDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
    'getDonor' : IDL.Func([IDL.Nat], [Donor], ['query']),
    'getDonorsByBloodGroup' : IDL.Func(
        [BloodGroup],
        [IDL.Vec(Donor)],
        ['query'],
      ),
    'markDonorAsDonated' : IDL.Func([IDL.Nat], [], []),
    'markDonorAsNotDonated' : IDL.Func([IDL.Nat], [], []),
    'recordCall' : IDL.Func([IDL.Nat], [], []),
    'updateDonorStatus' : IDL.Func([IDL.Nat, DonorStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };