/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type DonorStatus = {
    __kind__: "active";
    active: null;
} | {
    __kind__: "permanentlyRejected";
    permanentlyRejected: null;
} | {
    __kind__: "appointed";
    appointed: {
        appointmentDate: Time;
        patientName: string;
    };
} | {
    __kind__: "temporarilyRejected";
    temporarilyRejected: {
        availableDate: Time;
    };
};
export interface Donor {
    id: bigint;
    status: DonorStatus;
    name: string;
    bloodGroup: BloodGroup;
    phoneNumber: string;
}
export type Time = bigint;
export enum BloodGroup {
    AB_neg = "AB_neg",
    AB_pos = "AB_pos",
    B_neg = "B_neg",
    B_pos = "B_pos",
    A_neg = "A_neg",
    A_pos = "A_pos",
    O_neg = "O_neg",
    O_pos = "O_pos"
}
export interface backendInterface {
    addDonor(name: string, bloodGroup: BloodGroup, phoneNumber: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "error";
        error: string;
    }>;
    getAllAppointedDonors(): Promise<Array<Donor>>;
    getAllDonors(): Promise<Array<Donor>>;
    getAllPermanentlyRejectedDonors(): Promise<Array<Donor>>;
    getAllTempRejectedDonors(): Promise<Array<Donor>>;
    getDonor(id: bigint): Promise<{
        __kind__: "ok";
        ok: Donor;
    } | {
        __kind__: "error";
        error: string;
    }>;
    getDonorsByBloodGroup(bloodGroup: BloodGroup): Promise<Array<Donor>>;
    updateDonorStatus(donorId: bigint, newStatus: DonorStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "error";
        error: string;
    }>;
}
import type { BloodGroup as _BloodGroup, Donor as _Donor, DonorStatus as _DonorStatus, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDonor(arg0: string, arg1: BloodGroup, arg2: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "error";
        error: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonor(arg0, to_candid_BloodGroup_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonor(arg0, to_candid_BloodGroup_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAppointedDonors(): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointedDonors();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointedDonors();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDonors(): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonors();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonors();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPermanentlyRejectedDonors(): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPermanentlyRejectedDonors();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPermanentlyRejectedDonors();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTempRejectedDonors(): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTempRejectedDonors();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTempRejectedDonors();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonor(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: Donor;
    } | {
        __kind__: "error";
        error: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonor(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonor(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorsByBloodGroup(arg0: BloodGroup): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorsByBloodGroup(to_candid_BloodGroup_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorsByBloodGroup(to_candid_BloodGroup_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDonorStatus(arg0: bigint, arg1: DonorStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "error";
        error: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonorStatus(arg0, to_candid_DonorStatus_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonorStatus(arg0, to_candid_DonorStatus_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BloodGroup_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodGroup): BloodGroup {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_DonorStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorStatus): DonorStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Donor_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donor): Donor {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DonorStatus;
    name: string;
    bloodGroup: _BloodGroup;
    phoneNumber: string;
}): {
    id: bigint;
    status: DonorStatus;
    name: string;
    bloodGroup: BloodGroup;
    phoneNumber: string;
} {
    return {
        id: value.id,
        status: from_candid_DonorStatus_n7(_uploadFile, _downloadFile, value.status),
        name: value.name,
        bloodGroup: from_candid_BloodGroup_n9(_uploadFile, _downloadFile, value.bloodGroup),
        phoneNumber: value.phoneNumber
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AB_neg: null;
} | {
    AB_pos: null;
} | {
    B_neg: null;
} | {
    B_pos: null;
} | {
    A_neg: null;
} | {
    A_pos: null;
} | {
    O_neg: null;
} | {
    O_pos: null;
}): BloodGroup {
    return "AB_neg" in value ? BloodGroup.AB_neg : "AB_pos" in value ? BloodGroup.AB_pos : "B_neg" in value ? BloodGroup.B_neg : "B_pos" in value ? BloodGroup.B_pos : "A_neg" in value ? BloodGroup.A_neg : "A_pos" in value ? BloodGroup.A_pos : "O_neg" in value ? BloodGroup.O_neg : "O_pos" in value ? BloodGroup.O_pos : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Donor;
} | {
    error: string;
}): {
    __kind__: "ok";
    ok: Donor;
} | {
    __kind__: "error";
    error: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Donor_n5(_uploadFile, _downloadFile, value.ok)
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    error: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "error";
    error: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    error: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "error";
    error: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    permanentlyRejected: null;
} | {
    appointed: {
        appointmentDate: _Time;
        patientName: string;
    };
} | {
    temporarilyRejected: {
        availableDate: _Time;
    };
}): {
    __kind__: "active";
    active: null;
} | {
    __kind__: "permanentlyRejected";
    permanentlyRejected: null;
} | {
    __kind__: "appointed";
    appointed: {
        appointmentDate: Time;
        patientName: string;
    };
} | {
    __kind__: "temporarilyRejected";
    temporarilyRejected: {
        availableDate: Time;
    };
} {
    return "active" in value ? {
        __kind__: "active",
        active: value.active
    } : "permanentlyRejected" in value ? {
        __kind__: "permanentlyRejected",
        permanentlyRejected: value.permanentlyRejected
    } : "appointed" in value ? {
        __kind__: "appointed",
        appointed: value.appointed
    } : "temporarilyRejected" in value ? {
        __kind__: "temporarilyRejected",
        temporarilyRejected: value.temporarilyRejected
    } : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donor>): Array<Donor> {
    return value.map((x)=>from_candid_Donor_n5(_uploadFile, _downloadFile, x));
}
function to_candid_BloodGroup_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): _BloodGroup {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DonorStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonorStatus): _DonorStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "active";
    active: null;
} | {
    __kind__: "permanentlyRejected";
    permanentlyRejected: null;
} | {
    __kind__: "appointed";
    appointed: {
        appointmentDate: Time;
        patientName: string;
    };
} | {
    __kind__: "temporarilyRejected";
    temporarilyRejected: {
        availableDate: Time;
    };
}): {
    active: null;
} | {
    permanentlyRejected: null;
} | {
    appointed: {
        appointmentDate: _Time;
        patientName: string;
    };
} | {
    temporarilyRejected: {
        availableDate: _Time;
    };
} {
    return value.__kind__ === "active" ? {
        active: value.active
    } : value.__kind__ === "permanentlyRejected" ? {
        permanentlyRejected: value.permanentlyRejected
    } : value.__kind__ === "appointed" ? {
        appointed: value.appointed
    } : value.__kind__ === "temporarilyRejected" ? {
        temporarilyRejected: value.temporarilyRejected
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): {
    AB_neg: null;
} | {
    AB_pos: null;
} | {
    B_neg: null;
} | {
    B_pos: null;
} | {
    A_neg: null;
} | {
    A_pos: null;
} | {
    O_neg: null;
} | {
    O_pos: null;
} {
    return value == BloodGroup.AB_neg ? {
        AB_neg: null
    } : value == BloodGroup.AB_pos ? {
        AB_pos: null
    } : value == BloodGroup.B_neg ? {
        B_neg: null
    } : value == BloodGroup.B_pos ? {
        B_pos: null
    } : value == BloodGroup.A_neg ? {
        A_neg: null
    } : value == BloodGroup.A_pos ? {
        A_pos: null
    } : value == BloodGroup.O_neg ? {
        O_neg: null
    } : value == BloodGroup.O_pos ? {
        O_pos: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
